server:
  port: 8082
spring:
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: deepseek-v3
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "ai_health_assistant"
        collectionName: "dietary_guidelines"
        embeddingDimension: 1024
        indexType: FLAT
        metricType: COSINE
        auto-id: true
        id-field-name: id
        embedding-field-name: vector
        metadata-field-name: meata
        content-field-name: content
    memory:
      redis:
        host: localhost
        port: 6379
        timeout: 5000
        password:
    mcp:
      client:
        request-timeout: 60000
        stdio:
          # 1. 单独放在一个json文件（推荐）
#          servers-configuration: classpath:/mcp/mcp-servers-config.json
          #2. 直接配置全局配置文件中
          connections:
            mysql:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - '@fhuang/mcp-mysql-server'
                - mysql://root:J2bZ4wo07G8ntha@47.251.65.112:3306/datax

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

